import subprocess

def run(script):
    print(f"\n=== Running {script} ===")
    subprocess.run(["python", script], check=False)

run("hacr_core.py")
run("lens_engine.py")
run("matrix_engine.py")
run("drift_engine.py")
run("dependency_engine.py")
run("watchdog_engine.py")
run("topology_mapper.py")
run("topology_visualizer.py")
run("pricing_scope_engine.py")
run("signal_bridge_mapper.py")
run("condition_trace_mapper.py")
run("bind_freshness_checker.py")
run("language_simplifier.py")
run("reversal_asymmetry_lens.py")
run("receipt_integrity_chain.py")
run("dynamic_drift_lens.py")
run("semantic_asymmetry_lens.py")
run("alpha_omega_lineage_lens.py")
run("superposition_reachability_mapper.py")
run("cross_lens_correlation_engine.py")
run("topology_drift_timeline.py")
run("latent_path_detector.py")
run("authority_surface_mapper.py")
run("constructibility_collapse_mapper.py")
run("replay_vector_mapper.py")
run("lineage_consumption_auditor.py")
run("receipt_engine.py")

print("\nHACR Hybrid Observatory full run complete.")